'use strict';
// member data: url, jpn_name, eng_name, TODO: jpn_nick, eng_nick, kennin T/F

var nanagogo_groups = [
    {
        'title' : 'AKB48',
        'background' : '#FF47A3',
        'css_class' : 'akb48',
        'teams' : [
            {
                'title' : 'Team A',
                'background' : '#FD8EB3',
                'highlight' : '#f596b4',
                'css_class' : 'teama',
                'members' : [
                    // { 'jpn_name' : '入山杏奈'     : { 'url' : '', 'eng_name' : 'Iriyama Anna' },
                    { 'jpn_name' : '岩田華怜'     , 'url' : 'http://7gogo.jp/lp/pdAqgqtgPFAWkVIvojdMdG==', 'eng_name' : 'Iwata Karen' },
                    { 'jpn_name' : '小笠原茉由'   , 'url' : 'http://7gogo.jp/lp/34cMib_tE2LWkVIvojdMdG==', 'eng_name' : 'Ogasawara Mayu' },
                    { 'jpn_name' : '大和田南那'   , 'url' : 'http://7gogo.jp/lp/za4CH4HIu87WkVIvojdMdG==', 'eng_name' : 'Owada Nana' },
                    { 'jpn_name' : '大家志津香'   , 'url' : 'http://7gogo.jp/lp/SGo2TE6AAx-WkVIvojdMdG==', 'eng_name' : 'Oya Shizuka' },
                    { 'jpn_name' : '小嶋菜月'     , 'url' : 'http://7gogo.jp/lp/_Lpk-NZZSzEWkVIvojdMdG==', 'eng_name' : 'Kojima Natsuki' },
                    { 'jpn_name' : '小嶋陽菜'     , 'url' : 'http://7gogo.jp/lp/vY_r5fWR7IlWkVIvojdMdG==', 'eng_name' : 'Kojima Haruna' },
                    { 'jpn_name' : '佐々木優佳里' , 'url' : 'http://7gogo.jp/lp/qCdWye1yFdeWkVIvojdMdG==', 'eng_name' : 'Sasaki Yukari' },
                    { 'jpn_name' : '島崎遥香'     , 'url' : 'http://7gogo.jp/lp/mp3LH4G-d8LWkVIvojdMdG==', 'eng_name' : 'Shimazaki Haruka' },
                    { 'jpn_name' : '白間美瑠'     , 'url' : 'http://7gogo.jp/lp/dWtbBcuTI4tWkVIvojdMdG==', 'eng_name' : 'Shiroma Miru' },
                    { 'jpn_name' : '高橋みなみ'    , 'url' : 'http://7gogo.jp/lp/7yRhOGmxoKhWkVIvojdMdG==', 'eng_name' : 'Takahashi Minami' },
                    { 'jpn_name' : '田北香世子'   , 'url' : 'http://7gogo.jp/lp/w3De4uJkhUYWkVIvojdMdG==', 'eng_name' : 'Takita Kayoko' },
                    { 'jpn_name' : '谷口めぐ'      , 'url' : 'http://7gogo.jp/lp/feeeK4iBLaEWkVIvojdMdG==', 'eng_name' : 'Taniguchi Megu' },
                    { 'jpn_name' : '中西智代梨'   , 'url' : 'http://7gogo.jp/lp/ELMicfC5qphWkVIvojdMdG==', 'eng_name' : 'Nakanishi Chiyori' },
                    { 'jpn_name' : '中村麻里子'   , 'url' : 'http://7gogo.jp/lp/UKK9qKjtuxtWkVIvojdMdG==', 'eng_name' : 'Nakamura Mariko' },
                    { 'jpn_name' : '西山怜那'     , 'url' : 'http://7gogo.jp/lp/NAVdqtYXjrYWkVIvojdMdG==', 'eng_name' : 'Nishiyama Rena' },
                    { 'jpn_name' : '平田梨奈'     , 'url' : 'http://7gogo.jp/lp/MEAMz6W4JcRWkVIvojdMdG==', 'eng_name' : 'Hirata Rina' },
                    { 'jpn_name' : '前田亜美'     , 'url' : 'http://7gogo.jp/lp/BkoI5GQgTWRWkVIvojdMdG==', 'eng_name' : 'Maeda Ami' },
                    { 'jpn_name' : '宮崎美穂'     , 'url' : 'http://7gogo.jp/lp/7cVrRTmSjHYWkVIvojdMdG==', 'eng_name' : 'Miyazaki Miho' },
                    { 'jpn_name' : '宮脇咲良'     , 'url' : 'http://7gogo.jp/lp/zk0jj7dC0w1WkVIvojdMdG==', 'eng_name' : 'Miyawaki Sakura' },
                    { 'jpn_name' : '横山由依'     , 'url' : 'http://7gogo.jp/lp/2M575KWQ8qRWkVIvojdMdG==', 'eng_name' : 'Yokoyama Yui' },
                    // { 'jpn_name' : '山田菜々美'   , 'url' : '', 'eng_name' : 'Yamada Nanami' },
                ]
            },
            {
                'title' : 'Team K',
                'background' : '#64B000',
                'highlight' : '#83C033',
                'css_class' : 'teamk',
                'members' : [
                    { 'jpn_name' : '相笠萌'       , 'url' : 'http://7gogo.jp/lp/QskGSndOo7HWkVIvojdMdG==', 'eng_name' : 'Aigasa Moe' },
                    // { 'jpn_name' : '阿部マリア'     , 'url' : '', 'eng_name' : 'Abe Maria' ),
                    { 'jpn_name' : '石田晴香'     , 'url' : 'http://7gogo.jp/lp/dT4zuHTWQO-WkVIvojdMdG==', 'eng_name' : 'Ishida Haruka' },
                    { 'jpn_name' : '市川愛美'     , 'url' : 'http://7gogo.jp/lp/CrLRVXJvQ-EWkVIvojdMdG==', 'eng_name' : 'Ichikawa Manami' },
                    { 'jpn_name' : '兒玉遥'       , 'url' : 'http://7gogo.jp/lp/hiJUcq7tYoaWkVIvojdMdG==', 'eng_name' : 'Kodama Haruka' },
                    { 'jpn_name' : '篠崎彩奈'     , 'url' : 'http://7gogo.jp/lp/2GolEnidmfAWkVIvojdMdG==', 'eng_name' : 'Shinozaki Ayana' },
                    { 'jpn_name' : '島田晴香'     , 'url' : 'http://7gogo.jp/lp/BQksvx6o1o1WkVIvojdMdG==', 'eng_name' : 'Shimada Haruka' },
                    { 'jpn_name' : '下口ひなな'    , 'url' : 'http://7gogo.jp/lp/BO1k-YmgHZaWkVIvojdMdG==', 'eng_name' : 'Shimoguchi Hinana' },
                    { 'jpn_name' : '鈴木まりや'     , 'url' : 'http://7gogo.jp/lp/7tXReNFs0Y7WkVIvojdMdG==', 'eng_name' : 'Suzuki Mariya' },
                    { 'jpn_name' : '高城亜樹'     , 'url' : 'http://7gogo.jp/lp/XwmKlo1I1xxWkVIvojdMdG==', 'eng_name' : 'Takajo Aki' },
                    { 'jpn_name' : '田野優花'     , 'url' : 'http://7gogo.jp/lp/U-BFAd1TcCtWkVIvojdMdG==', 'eng_name' : 'Tano Yuka' },
                    // { 'jpn_name' : '中田ちさと'     , 'url' : '', 'eng_name' : 'Nakata Chisato' },
                    // { 'jpn_name' : '中野郁海'     , 'url' : '', 'eng_name' : 'Nakano Ikumi' },
                    { 'jpn_name' : '永尾まりや'     , 'url' : 'http://7gogo.jp/lp/7LwfEpd2OexWkVIvojdMdG==', 'eng_name' : 'Nagao Mariya' },
                    { 'jpn_name' : '藤田奈那'     , 'url' : 'http://7gogo.jp/lp/iYG4g2iR1EAWkVIvojdMdG==', 'eng_name' : 'Fujita Nana' },
                    { 'jpn_name' : '松井珠理奈'   , 'url' : 'http://7gogo.jp/lp/wgAO-66VrkRWkVIvojdMdG==', 'eng_name' : 'Matsui Jurina' },
                    { 'jpn_name' : '峯岸みなみ'    , 'url' : 'http://7gogo.jp/lp/4nXwYUY-vNaWkVIvojdMdG==', 'eng_name' : 'Minegishi Minami' },
                    { 'jpn_name' : '向井地美音'   , 'url' : 'http://7gogo.jp/lp/xJyc1EyBe-LWkVIvojdMdG==', 'eng_name' : 'Mukaichi Mion' },
                    { 'jpn_name' : '武藤十夢'     , 'url' : 'http://7gogo.jp/lp/HAvLciwSA0hWkVIvojdMdG==', 'eng_name' : 'Muto Tomu' },
                    { 'jpn_name' : '茂木忍'       , 'url' : 'http://7gogo.jp/lp/WFzHcGl0iolWkVIvojdMdG==', 'eng_name' : 'Mogi Shinobu' },
                    { 'jpn_name' : '湯本亜美'     , 'url' : 'http://7gogo.jp/lp/1wHIP97TSG-WkVIvojdMdG==', 'eng_name' : 'Yumoto Ami' },
                    { 'jpn_name' : '山本彩'       , 'url' : 'http://7gogo.jp/lp/YZhq2EGQ5OlWkVIvojdMdG==', 'eng_name' : 'Yamamoto Sayaka' },
                ]
            },
            {
                'title' : 'Team B', 
                'background' : '#26A6E0',
                'highlight' : '#51B8E6',
                'css_class' : 'teamb',
                'members' : [
                    { 'jpn_name' : '岩佐美咲',   'url' : 'http://7gogo.jp/lp/3bqg-OGYTbAWkVIvojdMdG==' , 'eng_name' : 'Iwasa Misaki' },
                    { 'jpn_name' : '内山奈月',   'url' : 'http://7gogo.jp/lp/BM4K0Q1uv7aWkVIvojdMdG==' , 'eng_name' : 'Uchiyama Natsuki' },
                    { 'jpn_name' : '梅田綾乃',   'url' : 'http://7gogo.jp/lp/J4_wY7MgKOHWkVIvojdMdG==' , 'eng_name' : 'Umeta Ayano' },
                    { 'jpn_name' : '大島涼花',   'url' : 'http://7gogo.jp/lp/iMwRMHpxvbRWkVIvojdMdG==' , 'eng_name' : 'Oshima Ryoka' },
                    { 'jpn_name' : '柏木由紀',   'url' : 'http://7gogo.jp/lp/LQ-C39d_3cLWkVIvojdMdG==' , 'eng_name' : 'Kashiwagi Yuki' },
                    { 'jpn_name' : '加藤玲奈',   'url' : 'http://7gogo.jp/lp/G38N5X0YdwEWkVIvojdMdG==' , 'eng_name' : 'Kato Rena' },
                    { 'jpn_name' : '木﨑ゆりあ',   'url' : 'http://7gogo.jp/lp/McormaXSKrtWkVIvojdMdG==' , 'eng_name' : 'Kizaki Yuria' },
                    { 'jpn_name' : '小林香菜',   'url' : 'http://7gogo.jp/lp/50r1rE6D9_YWkVIvojdMdG==' , 'eng_name' : 'Kobayashi Kana' },
                    { 'jpn_name' : '後藤萌咲',   'url' : 'http://7gogo.jp/lp/hU-5rjwXNlHWkVIvojdMdG==' , 'eng_name' : 'Goto Moe' },
                    // { 'jpn_name' : '坂口渚沙', 'url' : '' , 'eng_name' : 'Sakaguchi Nagisa' },
                    { 'jpn_name' : '竹内美宥',   'url' : 'http://7gogo.jp/lp/E6tFOYyih1LWkVIvojdMdG==' , 'eng_name' : 'Takeuchi Miyu' },
                    { 'jpn_name' : '達家真姫宝', 'url' : 'http://7gogo.jp/lp/GBsBNyoCIKHWkVIvojdMdG==' , 'eng_name' : 'Tatsuya Makiho' },
                    // { 'jpn_name' : '田名部生来', 'url' : '' , 'eng_name' : 'Tanabe Miku' },
                    { 'jpn_name' : '福岡聖菜',   'url' : 'http://7gogo.jp/lp/CwI1hUZJVytWkVIvojdMdG==' , 'eng_name' : 'Fukuoka Seina' },
                    { 'jpn_name' : '矢吹奈子',   'url' : 'http://7gogo.jp/lp/hk0DtyegB37WkVIvojdMdG==' , 'eng_name' : 'Yabuki Nako' },
                    { 'jpn_name' : '横島亜衿',   'url' : 'http://7gogo.jp/lp/IBTbf1yyMqoWkVIvojdMdG==' , 'eng_name' : 'Yokoshima Aeri' },
                    { 'jpn_name' : '渡辺麻友',   'url' : 'http://7gogo.jp/lp/ELruWTcySXaWkVIvojdMdG==' , 'eng_name' : 'Watanabe Mayu' },
                    { 'jpn_name' : '渡辺美優紀', 'url' : 'http://7gogo.jp/lp/v_a-HccnMnAWkVIvojdMdG==' , 'eng_name' : 'Watanabe Miyuki' }
                 ]
            },
            {
                'title' : 'Team 4',
                'background' : '#FCC300',
                'highlight' : '#FDCF33',
                'css_class' : 'team4',
                'members' : [
                    { 'jpn_name' : '飯野雅',       'url' : 'http://7gogo.jp/lp/Xk55QF08RGxWkVIvojdMdG==', 'eng_name' : 'Ino Miyabi' },
                    { 'jpn_name' : '伊豆田莉奈',   'url' : 'http://7gogo.jp/lp/T-s0bMuaGBYWkVIvojdMdG==', 'eng_name' : 'Izuta Rina' },
                    { 'jpn_name' : '岩立沙穂',     'url' : 'http://7gogo.jp/lp/XRwd8qOnWAtWkVIvojdMdG==', 'eng_name' : 'Iwatate Saho' },
                    { 'jpn_name' : '大川莉央',     'url' : 'http://7gogo.jp/lp/OIOvovwzUn1WkVIvojdMdG==', 'eng_name' : 'Okawa Rio' },
                    { 'jpn_name' : '大森美優',     'url' : 'http://7gogo.jp/lp/WSBoKbyhilAWkVIvojdMdG==', 'eng_name' : 'Omori Miyu' },
                    { 'jpn_name' : '岡田彩花',     'url' : 'http://7gogo.jp/lp/zRQZYlNiayaWkVIvojdMdG==', 'eng_name' : 'Okada Ayaka' },
                    { 'jpn_name' : '岡田奈々',     'url' : 'http://7gogo.jp/lp/zauwy0mkQMEWkVIvojdMdG==', 'eng_name' : 'Okada Nana' },
                    { 'jpn_name' : '川本紗矢',     'url' : 'http://7gogo.jp/lp/NJ6ICcu6jAEWkVIvojdMdG==', 'eng_name' : 'Kawamoto Saya' },
                    { 'jpn_name' : '北川綾巴',     'url' : 'http://7gogo.jp/lp/vYlii5lS_uhWkVIvojdMdG==', 'eng_name' : 'Kitagawa Ryoha' },
                    { 'jpn_name' : '北澤早紀',     'url' : 'http://7gogo.jp/lp/64WXKMlYbyAWkVIvojdMdG==', 'eng_name' : 'Kitazawa Saki' },
                    { 'jpn_name' : '小嶋真子',     'url' : 'http://7gogo.jp/lp/eBe2YkL562YWkVIvojdMdG==', 'eng_name' : 'Kojima Mako' },
                    { 'jpn_name' : '込山榛香',     'url' : 'http://7gogo.jp/lp/UjJQs3Z2ZqoWkVIvojdMdG==', 'eng_name' : 'Komiyama Haruka' },
                    { 'jpn_name' : '佐藤妃星',     'url' : 'http://7gogo.jp/lp/2wnVrVCtfsHWkVIvojdMdG==', 'eng_name' : 'Sato Kiara' },
                    { 'jpn_name' : '渋谷凪咲',     'url' : 'http://7gogo.jp/lp/hrVcFDqBQNEWkVIvojdMdG==', 'eng_name' : 'Shibuya Nagisa' },
                    { 'jpn_name' : '高橋朱里',     'url' : 'http://7gogo.jp/lp/CKsEN4V2yL1WkVIvojdMdG==', 'eng_name' : 'Takahashi Juri' },
                    { 'jpn_name' : '朝長美桜',     'url' : 'http://7gogo.jp/lp/-JNThk5XNf7WkVIvojdMdG==', 'eng_name' : 'Tomonaga Mio' },
                    { 'jpn_name' : '名取稚菜',     'url' : 'http://7gogo.jp/lp/06FOyWF-nuLWkVIvojdMdG==', 'eng_name' : 'Natori Wakana' },
                    { 'jpn_name' : '西野未姫',     'url' : 'http://7gogo.jp/lp/EdWOBsVVIPeWkVIvojdMdG==', 'eng_name' : 'Nishino Miki ' },
                    { 'jpn_name' : '野澤玲奈',     'url' : 'http://7gogo.jp/lp/NostAw7hhNeWkVIvojdMdG==', 'eng_name' : 'Nozawa Rena' },
                    { 'jpn_name' : '村山彩希',     'url' : 'http://7gogo.jp/lp/svh4UDoX4AhWkVIvojdMdG==', 'eng_name' : 'Murayama Yuiri' }
                ]
            },
            /* { 'jpn_name' : 'Team 8' }*/ /* Team 8 is not on 755 */
        ]
    },
    { 'jpn_name' : 'SKE48', 'empty' : true  },
    { 
        'title' : 'NMB48',
        'background' : 'url("http://i.imgur.com/jnTNkAK.png")', // this is why this property is called background and not color
        'css_class' : 'nmb48',
        'teams' : [
        {
            'title' : 'Team N',
            'background' : '#FAB900',
            'highlight' : '#FBC733',
            'css_class' : 'teamn',
            'members' : [
                { 'jpn_name' : '明石奈津子', 'url' : 'http://7gogo.jp/lp/iWErYED7LjhWkVIvojdMdG==', 'eng_name' : 'Akashi Natsuko' },
                { 'jpn_name' : '石田優美',   'url' : 'http://7gogo.jp/lp/K8Aua-B2Cn1WkVIvojdMdG==', 'eng_name' : 'Ishida Yuumi' },
                { 'jpn_name' : '太田夢莉',   'url' : 'http://7gogo.jp/lp/mHk4WVlPJDAWkVIvojdMdG==', 'eng_name' : 'Ota Yuuri' },
                { 'jpn_name' : '加藤夕夏',   'url' : 'http://7gogo.jp/lp/pDtF-Yvv_1YWkVIvojdMdG==', 'eng_name' : 'Kato Yuuka' },
                { 'jpn_name' : '岸野里香',   'url' : 'http://7gogo.jp/lp/5X3VP1vG6X1WkVIvojdMdG==', 'eng_name' : 'Kishino Rika' },
                { 'jpn_name' : '古賀成美',   'url' : 'http://7gogo.jp/lp/BOIoCQ5gg8tWkVIvojdMdG==', 'eng_name' : 'Koga Narumi' },
                { 'jpn_name' : '小谷里歩',   'url' : 'http://7gogo.jp/lp/547K3W6SzFoWkVIvojdMdG==', 'eng_name' : 'Kotani Riho' },
                { 'jpn_name' : '城恵理子',   'url' : 'http://7gogo.jp/lp/WhkCuH5ayL7WkVIvojdMdG==', 'eng_name' : 'Jo Eriko' },
                { 'jpn_name' : '上西恵',     'url' : 'http://7gogo.jp/lp/mj0SMU4NQJhWkVIvojdMdG==', 'eng_name' : 'Jonishi Kei' },
                { 'jpn_name' : '須藤凛々花', 'url' : 'http://7gogo.jp/lp/7tSSeQMl1blWkVIvojdMdG==', 'eng_name' : 'Sutou Ririka' },
                { 'jpn_name' : '西澤瑠莉奈', 'url' : 'http://7gogo.jp/lp/Np9eyF-wwheWkVIvojdMdG==', 'eng_name' : 'Nishizawa Rurina' },
                { 'jpn_name' : '西村愛華',   'url' : 'http://7gogo.jp/lp/IG0SmUPuf2xWkVIvojdMdG==', 'eng_name' : 'Nishimura Aika' },
                { 'jpn_name' : '山尾梨奈',   'url' : 'http://7gogo.jp/lp/DfI7x-TbGORWkVIvojdMdG==', 'eng_name' : 'Yamao Rina' },
                { 'jpn_name' : '山口夕輝',   'url' : 'http://7gogo.jp/lp/yY31zsHfx6xWkVIvojdMdG==', 'eng_name' : 'Yamaguchi Yuki' },
                { 'jpn_name' : '山本彩',     'url' : 'http://7gogo.jp/lp/YZhq2EGQ5OlWkVIvojdMdG==', 'eng_name' : 'Yamamoto Sayaka' },
                { 'jpn_name' : '吉田朱里',   'url' : 'http://7gogo.jp/lp/crOy5qfF3SeWkVIvojdMdG==', 'eng_name' : 'Yoshida Akari' }            
            ]
        },
        {
            'title' : 'Team M',
            'background' : '#E15A70',
            'highlight' : '#E77B8D',
            'css_class' : 'teamm',
            'members' : [
                { 'jpn_name' : '東由樹',      'url' : 'http://7gogo.jp/lp/-SztK55brZ7WkVIvojdMdG==', 'eng_name' : 'Azuma Yuki' },
                { 'jpn_name' : '石塚朱莉',    'url' : 'http://7gogo.jp/lp/bZ8XtEOfefEWkVIvojdMdG==', 'eng_name' : 'Ishizuka Akari' },
                { 'jpn_name' : '植村梓',      'url' : 'http://7gogo.jp/lp/Dym40tVlR3LWkVIvojdMdG==', 'eng_name' : 'Uemura Azusa' },
                // { 'jpn_name' : '鵜野みずき',    'url' : '', 'eng_name' : 'Uno Mizuki' },
                { 'jpn_name' : '沖田彩華',    'url' : 'http://7gogo.jp/lp/uItQhfyCSJlWkVIvojdMdG==', 'eng_name' : 'Okita Ayaka' },
                { 'jpn_name' : '川上礼奈',    'url' : 'http://7gogo.jp/lp/pQUMSFHzfjLWkVIvojdMdG==', 'eng_name' : 'Kawakami Rena' },
                // { 'jpn_name' : '木下百花',   'url' : '', 'eng_name' : 'Kinoshita Momoka' }, // of course she doesn't have one >_<
                { 'jpn_name' : '久代梨奈',    'url' : 'http://7gogo.jp/lp/9ej7G7GKBsLWkVIvojdMdG==', 'eng_name' : 'Kushiro Rina' },
                { 'jpn_name' : '近藤里奈',    'url' : 'http://7gogo.jp/lp/mWgcZcpityhWkVIvojdMdG==', 'eng_name' : 'Kondo Rina' },
                { 'jpn_name' : '白間美瑠',    'url' : 'http://7gogo.jp/lp/dWtbBcuTI4tWkVIvojdMdG==', 'eng_name' : 'Shiroma Miru' },
                { 'jpn_name' : '武井紗良',    'url' : 'http://7gogo.jp/lp/sigQfBoj2C-WkVIvojdMdG==', 'eng_name' : 'Takei Sara' },
                { 'jpn_name' : '谷川愛梨',    'url' : 'http://7gogo.jp/lp/e6DRzdKQSKeWkVIvojdMdG==', 'eng_name' : 'Tanigawa Airi' },
                { 'jpn_name' : '中野麗来',    'url' : 'http://7gogo.jp/lp/JtD11CWmSXYWkVIvojdMdG==', 'eng_name' : 'Nakano Reina' },
                { 'jpn_name' : '藤江れいな',   'url' : 'http://7gogo.jp/lp/rqJoIN5eLz7WkVIvojdMdG==', 'eng_name' : 'Fujie Reina' },
                { 'jpn_name' : '松村芽久未',  'url' : 'http://7gogo.jp/lp/Mo5ou5rYG7oWkVIvojdMdG==', 'eng_name' : 'Matsumura Megumi' },
                { 'jpn_name' : '三田麻央',    'url' : 'http://7gogo.jp/lp/KSwC3juFDuYWkVIvojdMdG==', 'eng_name' : 'Mita Mao' },
                { 'jpn_name' : '村瀬紗英',    'url' : 'http://7gogo.jp/lp/w40fBW9VINaWkVIvojdMdG==', 'eng_name' : 'Murase Sae' },
                { 'jpn_name' : '森田彩花',    'url' : 'http://7gogo.jp/lp/T7f4PpM9-T1WkVIvojdMdG==', 'eng_name' : 'Morita Ayaka' },
                { 'jpn_name' : '矢倉楓子',    'url' : 'http://7gogo.jp/lp/UPMYN57l-rlWkVIvojdMdG==', 'eng_name' : 'Yagura Fuuko' }
            ]
        },
        {
            'title' : 'Team BII',
            'background' : '#283CB4',
            'highlight' : '#3C5AC3',
            'css_class' : 'teambii',
            'members' : [
                { 'jpn_name' : '林萌々香',    'url' : 'http://7gogo.jp/lp/3kfCyisN7doWkVIvojdMdG==', 'eng_name' : 'Hayashi Momoka' },
                { 'jpn_name' : '市川美織',    'url' : 'http://7gogo.jp/lp/ax-PXUpuGLaWkVIvojdMdG==', 'eng_name' : 'Ichikawa Miori' },
                { 'jpn_name' : '井尻晏菜',    'url' : 'http://7gogo.jp/lp/mq0O9cSmRAoWkVIvojdMdG==', 'eng_name' : 'Ijiri Anna' },
                { 'jpn_name' : '磯佳奈江',    'url' : 'http://7gogo.jp/lp/GHw-otwSFoYWkVIvojdMdG==', 'eng_name' : 'Iso Kanae' },
                { 'jpn_name' : '門脇佳奈子',  'url' : 'http://7gogo.jp/lp/nUfn2aM4D5RWkVIvojdMdG==', 'eng_name' : 'Kadowaki Kanako' },
                { 'jpn_name' : '上枝恵美加',  'url' : 'http://7gogo.jp/lp/Qq__b7nUg4HWkVIvojdMdG==', 'eng_name' : 'Kamieda Emika' },
                { 'jpn_name' : '川上千尋',    'url' : 'http://7gogo.jp/lp/vrK6qsp6uXRWkVIvojdMdG==', 'eng_name' : 'Kawakami Chihiro' },
                { 'jpn_name' : '木下春奈',    'url' : 'http://7gogo.jp/lp/Y1QAQwNMhcAWkVIvojdMdG==', 'eng_name' : 'Kinoshita Haruna' },
                { 'jpn_name' : '日下このみ',   'url' : 'http://7gogo.jp/lp/dtSI5ZmwXhlWkVIvojdMdG==', 'eng_name' : 'Kusaka Konomi' },
                { 'jpn_name' : '黒川葉月',    'url' : 'http://7gogo.jp/lp/JF0LoFgncntWkVIvojdMdG==', 'eng_name' : 'Kurokawa Hazuki' },
                { 'jpn_name' : '松岡知穂',    'url' : 'http://7gogo.jp/lp/URICA4w5-ZlWkVIvojdMdG==', 'eng_name' : 'Matsuoka Chiho' },
                { 'jpn_name' : '内木志',      'url' : 'http://7gogo.jp/lp/u1wDiCGp72HWkVIvojdMdG==', 'eng_name' : 'Naiki Kokoro' },
                { 'jpn_name' : '大段舞依',    'url' : 'http://7gogo.jp/lp/EBk9AWBPBWLWkVIvojdMdG==', 'eng_name' : 'Odan Mai' },
                { 'jpn_name' : '渋谷凪咲',    'url' : 'http://7gogo.jp/lp/hrVcFDqBQNEWkVIvojdMdG==', 'eng_name' : 'Shibuya Nagisa' },
                { 'jpn_name' : '植田碧麗',    'url' : 'http://7gogo.jp/lp/yCqAyrzwU1EWkVIvojdMdG==', 'eng_name' : 'Ueda Mirei' },
                { 'jpn_name' : '梅田彩佳',    'url' : 'http://7gogo.jp/lp/qkImp3QBtt7WkVIvojdMdG==', 'eng_name' : 'Umeda Ayaka' },
                { 'jpn_name' : '渡辺美優紀',  'url' : 'http://7gogo.jp/lp/v_a-HccnMnAWkVIvojdMdG==', 'eng_name' : 'Watanabe Miyuki' },
                { 'jpn_name' : '薮下柊',      'url' : 'http://7gogo.jp/lp/mvXBiFDZRvxWkVIvojdMdG==', 'eng_name' : 'Yabushita Shu' }
            ]
        }]
    },
    { 'jpn_name' : 'HKT48', 'empty' : true  },
    { 'jpn_name' : 'NGT48', 'empty' : true  },
    // nogizaka formatting needs to be revised, or else just remove them from this list 
    /* { 'jpn_name' : 'Nogizaka46',
        'empty' : true,
        'Teams' : {
            'Nogizaka46' : {
                '秋元真夏': 'http://7gogo.jp/lp/EHJO22HByVYWkVIvojdMdG==',
                '生田絵梨花': 'http://7gogo.jp/lp/qVRNAvlchjLWkVIvojdMdG==',
                '生駒里奈': 'http://7gogo.jp/lp/jkOW8cD6yvaWkVIvojdMdG==',
                '伊藤かりん': 'http://7gogo.jp/lp/mQefyXKRyixWkVIvojdMdG==',
                '伊藤純奈': 'http://7gogo.jp/lp/QQIMkqI4yZLWkVIvojdMdG==',
                '井上小百合': 'http://7gogo.jp/lp/m2nb5PEEVF-WkVIvojdMdG==',
                '衛藤美彩': 'http://7gogo.jp/lp/IehN_dxcAlhWkVIvojdMdG==',
                '川後陽菜': 'http://7gogo.jp/lp/848OPG81AWtWkVIvojdMdG==',
                '川村まひろ': 'http://7gogo.jp/lp/EJjT0Dzb7XlWkVIvojdMdG==',
                '北野日奈子': 'http://7gogo.jp/lp/2Fl8X2eu81xWkVIvojdMdG==',
                '斎藤ちはる': 'http://7gogo.jp/lp/ZPRzeIO_rx-WkVIvojdMdG==',
                '斉藤優里': 'http://7gogo.jp/lp/WcgJ5NeKFhlWkVIvojdMdG==',
                '桜井玲香': 'http://7gogo.jp/lp/967Kcw7O3WLWkVIvojdMdG==',
                '白石麻衣': 'http://7gogo.jp/lp/-41Jgd7qLKLWkVIvojdMdG==',
                '新内眞衣': 'http://7gogo.jp/lp/CvkGFK1FrRAWkVIvojdMdG==',
                '高山一実': 'http://7gogo.jp/lp/slEyH7eOqmEWkVIvojdMdG==',
                '中田花奈': 'http://7gogo.jp/lp/MMhO048Vl1EWkVIvojdMdG==',
                '西野七瀬': 'http://7gogo.jp/lp/ipNEKvlo_eAWkVIvojdMdG==',
                '能條愛未': 'http://7gogo.jp/lp/sPHC9jWzi6xWkVIvojdMdG==',
                '橋本奈々未': 'http://7gogo.jp/lp/JitPAdGLEXaWkVIvojdMdG==',
                '星野みなみ': 'http://7gogo.jp/lp/JV4GaKQJZnaWkVIvojdMdG==',
                '堀未央奈': 'http://7gogo.jp/lp/59sEGXLHsYEWkVIvojdMdG==',
                '松村沙友理': 'http://7gogo.jp/lp/9SGk_al6McHWkVIvojdMdG==',
                '山崎怜奈': 'http://7gogo.jp/lp/loSdLlzZXdtWkVIvojdMdG==',
                '渡辺みり愛': 'http://7gogo.jp/lp/7J9xwxaZ77eWkVIvojdMdG==',
                '和田まあや': 'http://7gogo.jp/lp/5eM1jJlrHM1WkVIvojdMdG=='
            }
        }
    } */
];